logging:
  level:
    web: DEBUG
    com.rufeng.healthman: DEBUG
    org.springframework.security: DEBUG
    sql: DEBUG
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@rufeng20001123'
    url: jdbc:mysql://localhost:3306/healthman?serverTimezone=Asia/Shanghai
springdoc:
  swagger-ui:
    enabled: true
    path: /docs
  packages-to-scan: com.rufeng.healthman.controller