logging:
  level:
    web: DEBUG
    com.rufeng.healthman: DEBUG
    sql: DEBUG
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  swagger-ui:
    enabled: true
    path: /docs
  packages-to-scan: com.rufeng.healthman.controller
#  show-actuator: true
#  use-management-port: true